const DB = {
  CONNECTING: 'ON_CONNECT_DB_PENDING',
  CONNECTION_SUCCESS: 'ON_CONNECT_DB_SUCCESS',
  CONNECTION_FAILED: 'ON_CONNECT_DB_FAILED'
}

const ROUTE = {
  CHANGE: 'ON_ROUTE_CHANGE'
}

const GAMES = {
  CREATE_PENDING: 'ON_NEW_GAME_PENDING',
  CREATE_SUCCESS: 'ON_NEW_GAME_SUCCESS',
  CREATE_FAILED: 'ON_NEW_GAME_FAILED',
  GET_ALL_PENDING: 'ON_GAMES_REQUEST_PENDING',
  GET_ALL_SUCCESS: 'ON_GAMES_REQUEST_SUCCESS',
  GET_ALL_FAILED: 'ON_GAMES_REQUEST_FAILED'
}

export {
  DB,
  ROUTE,
  GAMES
}