const DB = {
  CONNECTING: "ON_CONNECT_DB_PENDING",
  CONNECTION_SUCCESS: "ON_CONNECT_DB_SUCCESS",
  CONNECTION_FAILED: "ON_CONNECT_DB_FAILED",
};

const ROUTE = {
  CHANGE: "ON_ROUTE_CHANGE",
};

const GAMES = {
  GAME_PENDING: "ON_NEW_GAME_PENDING",
  GAME_SUCCESS: "ON_NEW_GAME_SUCCESS",
  GAME_FAILED: "ON_NEW_GAME_FAILED",
  SET_GAME_SCORE: "SET_GAME_SCORE",
  GAME_SCORE_UPDATE: "ON_GAME_SCORE_UPDATE",
  ACTIVE_GAME_PENDING: "ACTIVE_GAME_PENDING",
  GAME_PENDING_STOP: "GAME_PENDING_STOP",
  SET_SELECTED_PLAYER: "SET_SELECTED_PLAYER",
  SET_PLAYER_STATS_PENDING: "SET_PLAYER_STATS_PENDING",
  SET_PLAYER_STATS_SUCCESS: "SET_PLAYER_STATS_SUCCESS",
  SET_PLAYER_STATS_FAILED: "SET_PLAYER_STATS_FAILED",
  SET_PLAYER_STATS_DIALOG: "SET_PLAYER_STATS_DIALOG",
  UPDATE_GAME_STATUS: "UPDATE_GAME_STATUS",
  UPDATE_GAME_STATUS_FAILED: "UPDATE_GAME_STATUS_FAILED",
  SET_GAME_STATUS: "SET_GAME_STATUS",
  SET_TEAM_FOULS: "SET_TEAM_FOULS",
  UPDATE_TEAM_FOULS: "UPDATE_TEAM_FOULS",
  SET_GAME_END_PROMPT: "SET_GAME_END_PROMPT",
  UPDATE_GAME_END: "UPDATE_GAME_END",
  SET_GAME_END: "SET_GAME_END",

  GET_ALL_PENDING: "ON_GAMES_REQUEST_PENDING",
  GET_ALL_SUCCESS: "ON_GAMES_REQUEST_SUCCESS",
  GET_ALL_FAILED: "ON_GAMES_REQUEST_FAILED",
};

const VENUES = {
  OPEN_NEW_VENUE_DIALOG: "OPEN_NEW_VENUE_DIALOG",
  CLOSE_NEW_VENUE_DIALOG: "CLOSE_NEW_VENUE_DIALOG",
};

const TEAMS = {
  SET_SELECTED: "TEAMS_SET_SELECTED",
  OPEN_NEW_TEAM_DIALOG: "OPEN_NEW_TEAM_DIALOG",
  CLOSE_NEW_TEAM_DIALOG: "CLOSE_NEW_TEAM_DIALOG",
};

const PLAYERS = {
  SET_SELECTED: "PLAYERS_SET_SELECTED",
  OPEN_NEW_PLAYERS_DIALOG: "OPEN_NEW_PLAYERS_DIALOG",
  CLOSE_NEW_PLAYERS_DIALOG: "CLOSE_NEW_PLAYERS_DIALOG",
};

const CLOCKS = {
  START_GAME_CLOCK: "START_GAME_CLOCK",
  STOP_GAME_CLOCK: "STOP_GAME_CLOCK",
  RESET_GAME_CLOCK: "RESET_GAME_CLOCK",
  SET_GAME_CLOCK: "SET_GAME_CLOCK",
  SET_GAME_CLOCK_START: "SET_GAME_CLOCK_START",
  START_ATTACK_CLOCK: "START_ATTACK_CLOCK",
  STOP_ATTACK_CLOCK: "STOP_ATTACK_CLOCK",
  RESET_ATTACK_CLOCK: "RESET_ATTACK_CLOCK",
  SET_ATTACK_CLOCK: "SET_ATTACK_CLOCK",
  SET_ATTACK_CLOCK_START: "SET_ATTACK_CLOCK_START",
  SET_ATTACK_CLOCK_TIMELEFT: "SET_ATTACK_CLOCK_TIMELEFT",
};

export { DB, ROUTE, GAMES, VENUES, TEAMS, PLAYERS, CLOCKS };
