export const ON_GAMES_REQUEST_PENDING = 'ON_GAMES_REQUEST_PENDING';
export const ON_GAMES_REQUEST_SUCCESS = 'ON_GAMES_REQUEST_SUCCESS';
export const ON_GAMES_REQUEST_FAILED = 'ON_GAMES_REQUEST_FAILED';