import { setRouteName } from './slices/routesSlice';

import { setSelectedTeam } from './slices/teamsSlice';

import {
  userSignup,
  userSignupSuccess,
  userLogin,
  verifyLogin,
  setLoggedIn,
  setLoggedInError,
  closeLogoutPrompt,
  openLogoutPrompt,
  userLogout,
  setLoggedOut,
  updatePassword,
  setUpdatePasswordSuccess,
  setUpdatePasswordFailed,
} from './slices/authSlice';

import {
  startGameClock,
  stopGameClock,
  resetGameClock,
  setGameClock,
  setGameClockStart,
} from './slices/gameClockSlice';

import {
  startAttackClock,
  stopAttackClock,
  resetAttackClock,
  setAttackClock,
  setAttackClockStart,
  setAttackClockTimeleft,
} from './slices/attackClockSlice';

import {
  startTimeoutClock,
  stopTimeoutClock,
  resetTimeoutClock,
  setTimeoutClock,
  setTimeoutClockStart,
} from './slices/timeoutClockSlice';

import {
  setGame,
  setGameEnd,
  setEndGameError,
  setEndGamePrompt,
  setGameScore,
  setGameSelectedPlayer,
  setGameStatus,
  setIsPlayerStatsDialog,
  setPlayerStats,
  setTeamFouls,
  updateGameEnd,
  updateGameScore,
  updateGameStatus,
  updateTeamFouls,
  updateTeamTimeouts,
  updatePlayerStats,
  updatePlayerStatsError,
  resetTeamFouls,
  setTeamTimeouts,
  resetTeamTimeouts,
  setIsTimeout,
  setIsTimeoutPrompt,
} from './slices/gameControlSlice';

export {
  userSignup,
  userSignupSuccess,
  userLogin,
  verifyLogin,
  setLoggedIn,
  setLoggedInError,
  userLogout,
  setLoggedOut,
  closeLogoutPrompt,
  openLogoutPrompt,
  updatePassword,
  setUpdatePasswordSuccess,
  setUpdatePasswordFailed,
  setRouteName,
  setSelectedTeam,
  startGameClock,
  stopGameClock,
  resetGameClock,
  setGameClock,
  setGameClockStart,
  startAttackClock,
  stopAttackClock,
  resetAttackClock,
  setAttackClock,
  setAttackClockStart,
  setAttackClockTimeleft,
  setGame,
  setGameEnd,
  setEndGameError,
  setEndGamePrompt,
  setGameScore,
  setGameSelectedPlayer,
  setGameStatus,
  setIsPlayerStatsDialog,
  setPlayerStats,
  setTeamFouls,
  updateGameEnd,
  updateGameScore,
  updateGameStatus,
  updateTeamFouls,
  updateTeamTimeouts,
  setTeamTimeouts,
  resetTeamTimeouts,
  updatePlayerStats,
  updatePlayerStatsError,
  resetTeamFouls,
  startTimeoutClock,
  stopTimeoutClock,
  resetTimeoutClock,
  setTimeoutClock,
  setTimeoutClockStart,
  setIsTimeout,
  setIsTimeoutPrompt,
};
