export const ON_CONNECT_DB_PENDING = 'ON_CONNECT_DB_PENDING';
export const ON_CONNECT_DB_SUCCESS = 'ON_CONNECT_DB_SUCCESS';
export const ON_CONNECT_DB_FAILED = 'ON_CONNECT_DB_FAILED';
export const ON_ROUTE_CHANGE = 'ON_ROUTE_CHANGE';